# Generated by Django 2.0.8 on 2019-08-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactions',
            name='last_session_id',
            field=models.IntegerField(default=0),
        ),
    ]
