# Generated by Django 2.0.8 on 2019-08-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions', '0002_reactions_last_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='last_session_id',
            field=models.TextField(default=''),
        ),
    ]
